### ISSUE TITLE
Violation of License! Copied Code.

### ISSUE THREAD

**Issue by codninja** [mgp25/Telegram-Bot-API#4]
It seems like you copied a lot of code and violated the License. I don't think its a good idea to take credits for others work.

You should consider giving proper credit and follow the license.

**Comment by mgp25** [comment]
@codninja i started this code from zero, all projects i do, i start always from zero, and as its very easy to have same things, because eveything is extracted from core Telegram API, as you can see here: https://core.telegram.org/bots/api

And if there is some code similarities it may be just coincidence, anyway good to know.

And just you to know, i never take credits of anyways project, this said, i close this issue.

You should check my projects and commits and all of my collaborations before saying this

**Comment by codninja** [comment]
@mgp25 The API docs do not tell you how to document the code.

What's your explanation for this:
[Original](https://github.com/irazasyed/telegram-bot-sdk/blob/master/src/Telegram.php#L420-L455) - [Copy](https://github.com/mgp25/Telegram-Bot-API/blob/master/src/Telegram.php#L298-L330)

Really? You talk about co-incidence, No chance there is any coincidence with documentation and the way its implemented.

Original:
https://github.com/irazasyed/telegram-bot-sdk/blob/master/src/Telegram.php#L487-L506
Copied:
https://github.com/mgp25/Telegram-Bot-API/blob/master/src/Telegram.php#L343-L358

Original:
https://github.com/irazasyed/telegram-bot-sdk/blob/master/src/Telegram.php#L370-L400
Copied:
https://github.com/mgp25/Telegram-Bot-API/blob/master/src/Telegram.php#L249-L278

How would you wanna explain this then?

**Comment by codninja** [comment]
You forgot you don't have a User Class but didn't bother to read properly before copy-pasting.

Original:
https://github.com/irazasyed/telegram-bot-sdk/blob/master/src/Telegram.php#L162-L175
Copied:
https://github.com/mgp25/Telegram-Bot-API/blob/master/src/Telegram.php#L20-L31

**Comment by mgp25** [comment]
@codninja check it https://core.telegram.org/bots/api#getme

And don't get mad about this, i told you i always code from zero all my projects, go to that url, and check, all descriptions are copied from the Core Telegram API (Link above), the only thing i took from external was the image you can find in the wiki that explains how to get the token.

Regards
